const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');const model=require('../career-model');
function setup({profile=null,prefs=null,path='/',pending=null,invite=null,user={id:'person'},fail=false}={}){
 const listeners={},ss=new Map(pending?[['goodcompany-onboarding-draft',JSON.stringify(pending)]]:[]),ls=new Map(invite?[['goodcompany-invite-return',JSON.stringify(invite)]]:[]);let target=null,saved=null;
 const store=m=>({getItem:k=>m.get(k)||null,setItem:(k,v)=>m.set(k,v),removeItem:k=>m.delete(k)});
 const client={from:table=>{let query={select:()=>query,eq:()=>query,maybeSingle:async()=>({data:table==='goodcompany_profiles'?profile:prefs,error:fail?{}:null}),upsert:value=>{saved=value;return query;},single:async()=>({data:saved,error:fail?{}:null})};return query;}};
 const window={GoodCompanyAccount:{getUser:()=>user,client},GoodCompanyCareerModel:model,addEventListener:(e,f)=>(listeners[e]??=[]).push(f),dispatchEvent:e=>(listeners[e.type]||[]).forEach(f=>f())};
 vm.runInNewContext(fs.readFileSync(require('node:path').join(__dirname,'../career.js'),'utf8'),{window,document:{getElementById:()=>null},URL,location:{origin:'https://in-good.company',pathname:path,search:'',hash:'',replace:url=>target=url},sessionStorage:store(ss),localStorage:store(ls),Event:class{constructor(type){this.type=type;}}});
 return {api:window.GoodCompanyCareer,target:()=>target,saved:()=>saved};
}
test('new users reach preferences before profile; existing users are not trapped',async()=>{let s=setup();assert(await s.api.routeAfterSignIn());assert(s.target().startsWith('onboarding.html'));s=setup({profile:{user_id:'person'}});assert.equal(await s.api.routeAfterSignIn(),false);s=setup({prefs:{onboarding_completed:true}});assert.equal(await s.api.routeAfterSignIn(),false);s=setup({path:'/onboarding.html'});assert.equal(await s.api.routeAfterSignIn(),false);});
test('invites survive onboarding, external redirects cannot escape the site',async()=>{let s=setup({invite:{id:'10000000-0000-4000-8000-000000000001',expires:Date.now()+100000}});await s.api.routeAfterSignIn();assert(decodeURIComponent(s.target()).includes('/profile.html?invite='));assert.equal(s.api.safeNext('https://evil.example/'),'/#directory');assert.equal(s.api.safeNext('/profile.html?id=123'),'/profile.html?id=123');});
test('preferences save independently and backend failures remain visible',async()=>{let s=setup();await s.api.load();await s.api.savePreferences({roles:['Product design']});assert(s.saved().onboarding_completed);assert.equal(s.saved().user_id,'person');assert.deepEqual(Array.from(s.saved().roles),['Product design']);s=setup({fail:true});assert.equal(await s.api.routeAfterSignIn(),false);await assert.rejects(()=>s.api.savePreferences({}),/weren’t saved/);});
