const {test}=require('node:test');const assert=require('node:assert/strict');const m=require('../career-model');
const job={id:'test',title:'Senior Product Designer',category:'Product design',disciplines:['AI Creative'],summary:'Build accessible design systems in Figma. Prototype with React and AI tools.',workplace:'Hybrid',workplaceOptions:['Hybrid','Remote']};
const profile={first_name:'Test',last_name:'Creative',bio:'Product designer',work_history:[{company:'Example',role:'Product designer',years:'2020–2024',accomplishments:'Built design systems in Figma.\nMade prototypes in React.'}]};
test('empty history never produces a fabricated score',()=>{assert.equal(m.fit(job).score,null);assert.equal(m.fit(job,{bio:'Figma React AI'}).score,null);assert.equal(m.fit({title:'Unrecognized role'},profile).score,null);});
test('fit is evidence-based and does not use identity',()=>{const r=m.fit(job,profile);assert(r.matched.some(x=>x.label==='Figma'&&x.evidence.includes('Figma')));assert.equal(r.score,Math.round(r.matched.length/r.total*100));assert.deepEqual(r,m.fit(job,{...profile,first_name:'Different',avatar_path:'photo'}));});
test('pasted resume replaces profile evidence',()=>{const r=m.fit(job,profile,'I spent three years creating brand campaigns and illustration work for several national client campaigns.');assert.equal(r.matched.length,0);assert.equal(r.score,0);});
test('multi-discipline and work setup preferences; missing industry stays unknown',()=>{const p=m.preferences(job,{roles:['AI Creative'],work_setups:['Remote'],industries:['Finance & fintech']},{},{});assert(p[0].match);assert(p[2].match);assert(p[1].unknown);assert(!p[1].match);});
test('industry inference explicit and invalid preferences ignored',()=>{const p=m.preferences(job,{industries:['AI & machine learning']},{about:'Software for generative AI.'});assert(p[0].inferred&&p[0].match);assert.deepEqual(m.cleanPreferences({roles:['fake','Product design','Product design']}).roles,['Product design']);});
test('draft preserves facts and never injects requirements',()=>{const d=m.draft(job,profile);assert(d.includes('2020–2024')&&d.includes('Example')&&d.includes('Built design systems in Figma.'));assert(!d.includes('accessible')&&!d.includes('Senior'));assert.equal(m.draft(job,profile,'My exact résumé'),'My exact résumé');});
