const {test}=require('node:test');const assert=require('node:assert/strict');const path=require('node:path');
process.chdir(path.join(__dirname,'..'));const handler=require('../api/resume-refine');
const body={jobId:'lovable-brand-designer-web-76f4a6',draft:'Test Creative\nDesigner at Example Studio, 2020–2024.\nCreated three brand websites using Figma and Webflow.',consent:true};
async function request({method='POST',authorization='Bearer fake.test.token',data=body,oidc}={}){let status,result,headers={};const res={setHeader:(k,v)=>headers[k]=v,status:n=>{status=n;return res;},json:value=>{result=value;return res;}};await handler({method,headers:{authorization,'x-vercel-oidc-token':oidc},body:data},res);return {status,result,headers};}
test('API enforces auth, consent, method and valid job before AI',async()=>{const old=global.fetch;global.fetch=()=>{throw Error('Network should not run');};try{assert.equal((await request({method:'GET'})).status,405);assert.equal((await request({authorization:''})).status,401);assert.equal((await request({data:{...body,consent:false}})).status,400);assert.equal((await request({data:{...body,jobId:'missing'}})).status,404);}finally{global.fetch=old;}});
test('validated user and atomic quota precede AI; only a full completion returned',async()=>{const old=global.fetch,key=process.env.AI_GATEWAY_API_KEY;process.env.AI_GATEWAY_API_KEY='test-key';let calls=[];global.fetch=async(url,opts)=>{calls.push(url);if(url.includes('/auth/'))return {ok:true,json:async()=>({id:'test-user'})};if(url.includes('/rpc/'))return {ok:true,json:async()=>true};const payload=JSON.parse(opts.body);assert.equal(payload.model,'anthropic/claude-haiku-4.5');assert(!payload.messages[0].content.includes('fake.test.token'));return {ok:true,json:async()=>({choices:[{finish_reason:'stop',message:{content:body.draft}}]})};};try{const r=await request();assert.equal(r.status,200);assert.equal(r.result.text,body.draft);assert.equal(calls.length,3);assert.equal(r.headers['Cache-Control'],'private, no-store');}finally{global.fetch=old;if(key===undefined)delete process.env.AI_GATEWAY_API_KEY;else process.env.AI_GATEWAY_API_KEY=key;}});
test('quota failure and truncated output never replace original',async()=>{const old=global.fetch,key=process.env.AI_GATEWAY_API_KEY;process.env.AI_GATEWAY_API_KEY='test-key';let quota=false,aiCalls=0;global.fetch=async url=>url.includes('/auth/')?{ok:true,json:async()=>({id:'test-user'})}:url.includes('/rpc/')?{ok:true,json:async()=>quota}:(aiCalls++,{ok:true,json:async()=>({choices:[{finish_reason:'length',message:{content:'Truncated'}}]})});try{assert.equal((await request()).status,429);assert.equal(aiCalls,0);quota=true;assert.equal((await request()).status,503);}finally{global.fetch=old;if(key===undefined)delete process.env.AI_GATEWAY_API_KEY;else process.env.AI_GATEWAY_API_KEY=key;}});

test('deployed requests use the request-scoped OIDC token without an env key',async()=>{const old=global.fetch,key=process.env.AI_GATEWAY_API_KEY,oidc=process.env.VERCEL_OIDC_TOKEN;delete process.env.AI_GATEWAY_API_KEY;delete process.env.VERCEL_OIDC_TOKEN;global.fetch=async(url,opts)=>{if(url.includes('/auth/'))return {ok:true,json:async()=>({id:'test-user'})};if(url.includes('/rpc/'))return {ok:true,json:async()=>true};assert.equal(opts.headers.Authorization,'Bearer test-request-oidc');return {ok:true,json:async()=>({choices:[{finish_reason:'stop',message:{content:body.draft}}]})};};try{assert.equal((await request({oidc:'test-request-oidc'})).status,200);}finally{global.fetch=old;if(key!==undefined)process.env.AI_GATEWAY_API_KEY=key;if(oidc!==undefined)process.env.VERCEL_OIDC_TOKEN=oidc;}});
